version: '3.9'

networks: 
    tick-stack-net:
        driver: bridge

volumes:
    tick-stack-data:

services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "telegraph"
            INFLUXDB_ADMIN_USER: "tick-stack-user"
            INFLUXDB_ADMIN_PASSWORD: "tick-stack-pwd"
        networks: 
            - tick-stack-net
        volumes:
            - ./influxdb/data:/var/lib/influxdb
        ports:
        # The API for InfluxDB is served on port 8086
        - "8086:8086"
        - "8082:8082"
        # UDP Port
        - "8089:8089/udp"

    telegraf:
        image: telegraf:latest
        depends_on: 
            - "influxdb"
        links: 
            - "influxdb"
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "telegraph"
        volumes:
            - ./telegraf/:/etc/telegraf/
            - /var/run/docker.sock:/var/run/docker.sock
        tty: true
        networks: 
            - tick-stack-net
        privileged: true
        
    kapacitor:
        image: kapacitor:latest
        container_name: kapacitor
        depends_on: 
            - "influxdb"
        links: 
            - "influxdb"
        ports:
            - 9092:9092
        environment:
            HOST_NAME: "kapacitor"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "telegraph"
        volumes:
            - ./kapacitor/data/:/var/lib/kapacitor
        networks: 
            - tick-stack-net
    
    chronograf:
        image: chronograf:latest
        container_name: chronograf
        depends_on: 
            - "influxdb"
            - "kapacitor"
        links: 
            - "influxdb"
            - "kapacitor"
        ports:
            - mode: ingress
              target: 8888
              published: 8001
              protocol: tcp
        environment:
            HOST_NAME: "chronograf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "telegraph"
            KAPACITOR_HOST: "kapacitor"
            KAPACITOR_PORT: "9092"
        volumes:
            - ./chronograf/data/:/var/lib/chronograf/
        networks: 
            - tick-stack-net

        
    